version: '1'
services:
  web:
    image: trading_api_web
    container_name: trading_api_web
    restart: always
    ports:
      - 8000:8000
#    command: bash -c /usr/src/app/start.sh
#    env_file: .env