version: '1'
services:
  app:
    build:
      context: .
    volumes:
      - .:/usr/src/app
    image: trading_api_web
    container_name: trading_api_web
    restart: always
    ports:
      - 8000:8000
