# Generated by Django 4.2.7 on 2023-11-23 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('auctionID', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=45)),
                ('description', models.CharField(max_length=255)),
                ('imagePath', models.ImageField(blank=True, null=True, upload_to='profile')),
                ('startingPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('buyOutPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('startTime', models.DateTimeField(auto_now_add=True)),
                ('endTime', models.DateTimeField()),
                ('auctionOwner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(allow_unicode=True, max_length=45, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('shipmentID', models.AutoField(primary_key=True, serialize=False)),
                ('bidAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid', models.BooleanField(default=False)),
                ('shipped', models.BooleanField(default=False)),
                ('shippingDetails', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('auctionID', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.auction')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profilePicPath', models.ImageField(blank=True, null=True, upload_to='profile')),
                ('userid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='auction',
            name='category',
            field=models.ManyToManyField(to='website.category'),
        ),
        migrations.AddField(
            model_name='auction',
            name='subscribed',
            field=models.ManyToManyField(blank=True, related_name='SubscribedUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auction',
            name='winnerID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='WinnerID', to=settings.AUTH_USER_MODEL),
        ),
    ]
