# Generated by Django 4.2.7 on 2023-11-13 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="id",
        ),
        migrations.AlterField(
            model_name="user",
            name="UserID",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
