# Generated by Django 4.2.7 on 2023-11-13 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0002_remove_user_id_alter_user_userid"),
    ]

    operations = [
        migrations.CreateModel(
            name="Auctions",
            fields=[
                ("AuctionId", models.AutoField(primary_key=True, serialize=False)),
                ("Description", models.CharField(max_length=255)),
                ("ImagePath", models.CharField(max_length=45)),
                ("Category", models.CharField(max_length=45)),
                ("StartingPrice", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "BuyOutPrice",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10),
                ),
                ("StartTime", models.DateTimeField(auto_now_add=True)),
                ("EndTime", models.DateTimeField()),
                (
                    "AuctionOwnerID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="website.user"
                    ),
                ),
                (
                    "WinnerID",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="WinnerID",
                        to="website.user",
                    ),
                ),
            ],
        ),
    ]
