# Generated by Django 4.2.7 on 2023-11-13 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0003_auctions"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Auctions",
            new_name="Auction",
        ),
    ]
