# Generated by Django 4.2.7 on 2023-11-13 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0004_rename_auctions_auction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auction",
            name="WinnerID",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="WinnerID",
                to="website.user",
            ),
        ),
    ]
