# Generated by Django 4.2.7 on 2023-11-13 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0005_alter_auction_winnerid"),
    ]

    operations = [
        migrations.AddField(
            model_name="auction",
            name="Title",
            field=models.CharField(max_length=45, null=True),
        ),
    ]
