# Generated by Django 4.2.7 on 2023-11-13 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0006_auction_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auction",
            name="Title",
            field=models.CharField(max_length=45),
        ),
    ]
