# Generated by Django 4.2.7 on 2023-11-28 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_subcategory_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='name',
            new_name='subcategory_name',
        ),
    ]
