# Generated by Django 4.2.7 on 2023-11-13 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0007_alter_auction_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("CategoryId", models.AutoField(primary_key=True, serialize=False)),
                ("Name", models.CharField(max_length=45)),
            ],
        ),
        migrations.RenameField(
            model_name="auction",
            old_name="AuctionId",
            new_name="AuctionID",
        ),
        migrations.RemoveField(
            model_name="auction",
            name="Category",
        ),
        migrations.CreateModel(
            name="Shipments",
            fields=[
                ("ShipmentID", models.AutoField(primary_key=True, serialize=False)),
                ("Paid", models.BooleanField(default=False)),
                ("Shipped", models.BooleanField(default=False)),
                ("ShippingDetails", models.CharField(max_length=255)),
                ("Timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "AuctionID",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="website.auction",
                    ),
                ),
                (
                    "BidAmount",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="BidAmount",
                        to="website.auction",
                    ),
                ),
                (
                    "UserID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="website.user"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="auction",
            name="Category",
            field=models.ManyToManyField(to="website.category"),
        ),
    ]
