# Generated by Django 4.2.7 on 2023-11-13 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0008_category_rename_auctionid_auction_auctionid_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Shipments",
            new_name="Shipment",
        ),
    ]
