# Generated by Django 4.2.7 on 2023-11-13 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0009_rename_shipments_shipment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auction",
            name="BuyOutPrice",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
