# Generated by Django 4.2.7 on 2023-12-06 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_remove_auction_category_auction_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.category'),
        ),
    ]
