# Generated by Django 4.2.7 on 2023-11-13 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0010_alter_auction_buyoutprice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shipment",
            name="BidAmount",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
