# Generated by Django 4.2.7 on 2023-11-13 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0011_alter_shipment_bidamount"),
    ]

    operations = [
        migrations.AddField(
            model_name="auction",
            name="Subscribed",
            field=models.ManyToManyField(
                related_name="SubscribedUser", to="website.user"
            ),
        ),
    ]
