# Generated by Django 4.2.7 on 2023-12-27 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0011_auction_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shipment",
            name="bidAmount",
        ),
    ]
