# Generated by Django 4.2.7 on 2023-11-13 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0012_auction_subscribed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auction",
            name="Subscribed",
            field=models.ManyToManyField(
                blank=True, related_name="SubscribedUser", to="website.user"
            ),
        ),
    ]
