# Generated by Django 4.2.7 on 2023-11-13 19:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("website", "0013_alter_auction_subscribed"),
    ]

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                ("UserID", models.AutoField(primary_key=True, serialize=False)),
                ("ProfilePicPath", models.CharField(max_length=255)),
                ("AuthLevel", models.IntegerField()),
                (
                    "Username",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="auction",
            name="AuctionOwnerID",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="auction",
            name="Subscribed",
            field=models.ManyToManyField(
                blank=True, related_name="SubscribedUser", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="auction",
            name="WinnerID",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="WinnerID",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="UserID",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
