# Generated by Django 4.2.7 on 2023-11-13 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0014_member_alter_auction_auctionownerid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shipment",
            name="AuctionID",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="website.auction",
            ),
        ),
    ]
