# Generated by Django 4.2.7 on 2023-11-13 22:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("website", "0015_alter_shipment_auctionid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="shipment",
            old_name="UserID",
            new_name="Username",
        ),
        migrations.RemoveField(
            model_name="member",
            name="UserID",
        ),
        migrations.AlterField(
            model_name="member",
            name="Username",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
