# Generated by Django 4.2.7 on 2023-11-13 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "website",
            "0016_rename_userid_shipment_username_remove_member_userid_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="auction",
            old_name="AuctionOwnerID",
            new_name="AuctionOwner",
        ),
        migrations.AlterField(
            model_name="category",
            name="Name",
            field=models.CharField(max_length=45, unique=True),
        ),
    ]
