# Generated by Django 4.2.7 on 2023-11-13 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0018_member_id_alter_member_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="member",
            name="AuthLevel",
        ),
        migrations.AlterField(
            model_name="member",
            name="ProfilePicPath",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
